export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const GET_USERS_STATE = 'GET_USERS_STATE';
export const CREATE_USERS_STATE = 'CREATE_USERS_STATE';
export const GET_RESSOURCE_STATE = 'GET_RESSOURCE_STATE';
